Repository FESP-8/PixelBeat, pull requests merged in 2023-12, with the labels that each got.

#2 📝 docs: 환경설정 초기 세팅
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .gitmessage
  index.html
  package-lock.json
  package.json
  postcss.config.js
  public/vite.svg
  src/components/ErrorComponent.tsx
  src/components/index.ts
  src/constants/buttonText.ts
  src/constants/errorText.ts
  src/constants/genre.ts
  src/constants/index.ts
  src/constants/receiptText.ts
  src/index.css
  src/main.tsx
  src/pages/Entry.tsx
  src/pages/Layout.tsx
  src/pages/Router.tsx
  src/pages/index.ts
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: 기능 추가

#5 ✨ feat: 추천 로직에 따른 라우터 추가 및 레이아웃 구현#3
  src/api/axios.ts
  src/assets/PixerBorder.svg
  src/assets/icons/Acoustic.tsx
  src/assets/icons/Animation.tsx
  src/assets/icons/Blues.tsx
  src/assets/icons/Chill.tsx
  src/assets/icons/Classic.tsx
  src/assets/icons/Dance.tsx
  src/assets/icons/Electonic.tsx
  src/assets/icons/Hiphop.tsx
  src/assets/icons/Indie.tsx
  src/assets/icons/Jazz.tsx
  src/assets/icons/Jpop.tsx
  src/assets/icons/Kid.tsx
  src/assets/icons/Kpop.tsx
  src/assets/icons/Movie.tsx
  src/assets/icons/PixelBorder.tsx
  src/assets/icons/Pop.tsx
  src/assets/icons/RnB.tsx
  src/assets/icons/Rock.tsx
  src/assets/icons/WorkOut.tsx
  src/assets/icons/index.ts
  src/assets/index.ts
  src/components/ErrorComponent.tsx
  src/components/common/StandardButton.tsx
  src/components/common/index.ts
  src/components/index.ts
  src/components/recommend/ArtistSelector.tsx
  src/components/recommend/GenreItem.tsx
  src/components/recommend/GenreSelector.tsx
  src/components/recommend/SongSelector.tsx
  src/components/recommend/index.tsx
  src/constants/recommned/index.ts
  src/constants/recommned/recommendText.tsx
  src/index.css
  src/main.tsx
  src/pages/Entry.tsx
  src/pages/Layout.tsx
  src/pages/Recommend.tsx
  src/pages/Router.tsx
  src/pages/index.ts
  src/zustand/index.ts
  src/zustand/recommendStore.ts
  tailwind.config.js
  tsconfig.json
Labels: 기능 추가

#10 ⚙️ config: eslint prettier 설정
  .eslintrc.json
  .prettierrc
  package-lock.json
  package.json
Labels: 설정

#13 ✨ feat: 장르 추천 API 연결
  src/api/axios.ts
  src/api/getNonMemberToken.ts
  src/api/index.ts
  src/api/recommendApis.ts
  src/api/supabase/client.ts
  src/api/supabase/index.ts
  src/api/supabase/tableAccessApis.ts
  src/assets/icons/Acoustic.tsx
  src/assets/icons/Blues.tsx
  src/assets/icons/Classic.tsx
  src/assets/icons/Kpop.tsx
  src/assets/icons/PixelBorder.tsx
  src/assets/icons/index.ts
  src/assets/icons/recommend/Acoustic.tsx
  src/assets/icons/recommend/Animation.tsx
  src/assets/icons/recommend/Blues.tsx
  src/assets/icons/recommend/Chill.tsx
  src/assets/icons/recommend/Classic.tsx
  src/assets/icons/recommend/Dance.tsx
  src/assets/icons/recommend/Electonic.tsx
  src/assets/icons/recommend/Hiphop.tsx
  src/assets/icons/recommend/Indie.tsx
  src/assets/icons/recommend/Jazz.tsx
  src/assets/icons/recommend/Jpop.tsx
  src/assets/icons/recommend/Kid.tsx
  src/assets/icons/recommend/Kpop.tsx
  src/assets/icons/recommend/Movie.tsx
  src/assets/icons/recommend/Pop.tsx
  src/assets/icons/recommend/RnB.tsx
  src/assets/icons/recommend/Rock.tsx
  src/assets/icons/recommend/WorkOut.tsx
  src/assets/icons/recommend/index.ts
  src/components/ErrorComponent.tsx
  src/components/common/StandardButton.tsx
  src/components/common/StandardPixelBorder.tsx
  src/components/common/StandardVertex.tsx
  src/components/recommend/ArtistItem.tsx
  src/components/recommend/ArtistSelector.tsx
  src/components/recommend/GenreItem.tsx
  src/components/recommend/GenreSelector.tsx
  src/components/recommend/SongSelector.tsx
  src/components/recommend/TrackSelector.tsx
  src/components/recommend/index.tsx
  src/constants/buttonText.ts
  src/constants/errorText.ts
  src/constants/genre.ts
  src/constants/receiptText.ts
  src/constants/recommned/index.ts
  src/constants/recommned/recommendText.tsx
  src/index.css
  src/main.tsx
  src/pages/Bill.tsx
  src/pages/Entry.tsx
  src/pages/Layout.tsx
  src/pages/Recommend.tsx
  src/pages/index.ts
  src/zustand/index.ts
  src/zustand/recommendStore.ts
  tailwind.config.js
  tsconfig.json
Labels: 기능 추가

#15 ✨feat: 추천 로직 구현 #14
  src/api/recommendApis.ts
  src/assets/icons/index.ts
  src/assets/icons/play/CirclePlaySmall.tsx
  src/assets/icons/play/index.ts
  src/components/bill/BillChartOption.ts
  src/components/bill/BillGraph.tsx
  src/components/bill/BillItem.tsx
  src/components/bill/index.ts
  src/components/home/Banner.tsx
  src/components/home/Header.tsx
  src/components/home/NavBar.tsx
  src/components/home/SimilarUser.tsx
  src/components/home/TopTrackList.tsx
  src/components/home/index.tsx
  src/components/recommend/TrackItem.tsx
  src/components/recommend/TrackSelector.tsx
  src/components/recommend/index.tsx
  src/index.css
  src/pages/Bill.tsx
  src/pages/Entry.tsx
  src/pages/Home.tsx
  src/pages/Router.tsx
  src/pages/index.ts
  src/utils/getRandomArray.ts
  src/utils/index.ts
  src/zustand/recommendStore.ts
Labels: 기능 추가

#20 ✨ feat: 추천 로직 수정 및 Bill database 연결
  src/api/supabase/client.ts
  src/api/supabase/tableAccessApis.ts
  src/assets/icons/index.ts
  src/components/bill/BillGraph.tsx
  src/components/bill/BillItem.tsx
  src/components/recommend/ArtistSelector.tsx
  src/components/recommend/GenreSelector.tsx
  src/components/recommend/TrackItem.tsx
  src/components/recommend/TrackSelector.tsx
  src/index.css
  src/pages/Bill.tsx
  src/pages/Layout.tsx
  src/pages/Recommend.tsx
  src/pages/Router.tsx
  src/types/index.ts
  src/types/tracklist.ts
  src/types/user.ts
  src/utils/formatDateTime.ts
  src/utils/index.ts
  src/zustand/recommendStore.ts
  tailwind.config.js
Labels: 기능 추가

#21 🐛 fix: 추천 로직 수정 및 Bill database 연결 및 추가 설정
  src/components/common/PlayBar.tsx
  src/pages/Bill.tsx
  src/zustand/index.ts
  src/zustand/nowPlayStore.ts
Labels: 버그

#28 ✨ feat: 바텀 시트 구현 #26
  index.html
  src/assets/icons/BottomSheetTop.tsx
  src/assets/icons/MoreButton.tsx
  src/assets/icons/index.ts
  src/components/artist/ArtistTopTrack.tsx
  src/components/common/BottomSheet.tsx
  src/components/common/index.ts
  src/components/search/SearchResultArtistItem.tsx
  src/components/search/SearchResultTrackItem.tsx
  src/components/search/SearchResultWrap.tsx
  src/hooks/index.ts
  src/hooks/useModal.tsx
  src/index.css
  src/pages/Artist.tsx
  src/utils/index.ts
  src/utils/portal.ts
  src/zustand/index.ts
  src/zustand/modalStore.ts
Labels: 기능 추가, 스타일

#30 ✨ feat: 음악 미리듣기 재생 페이지 및 Playbar 기능 구현 및 마크업
  src/assets/icons/ArrowDown.tsx
  src/assets/icons/index.ts
  src/assets/icons/play/CirclePause.tsx
  src/assets/icons/play/CirclePlay.tsx
  src/assets/icons/play/MusicList.tsx
  src/assets/icons/play/NextPlay.tsx
  src/assets/icons/play/Pause.tsx
  src/assets/icons/play/Play.tsx
  src/assets/icons/play/PrevPlay.tsx
  src/assets/icons/play/SoundOff.tsx
  src/assets/icons/play/SoundOn.tsx
  src/assets/icons/play/index.ts
  src/assets/imgs/playnowBtnBackground.png
  src/assets/imgs/progressDot.png
  src/components/common/Header.tsx
  src/components/common/PlayBar.tsx
  src/components/common/Playnow.tsx
  src/components/common/ProgressBar.tsx
  src/components/common/StandardButton.tsx
  src/components/common/index.ts
  src/hooks/index.ts
  src/hooks/useModal.ts
  src/hooks/usePlayAndPausePreview.ts
  src/index.css
  src/pages/Bill.tsx
  src/pages/Entry.tsx
  src/pages/Login.tsx
  src/pages/LoginEmail.tsx
  src/pages/Recommend.tsx
  src/pages/RecommendEntry.tsx
  src/pages/Router.tsx
  src/pages/index.ts
  src/utils/portal.ts
  src/zustand/modalStore.ts
  src/zustand/nowPlayStore.ts
Labels: 기능 추가, 스타일, 수정 (리팩토링)

#33 ✨ feat: home에서 미리듣기 기능 구현 및 배너 마크업
  package-lock.json
  package.json
  src/api/albumApi.ts
  src/api/artistApi.ts
  src/api/index.ts
  src/api/playlistApi.ts
  src/api/recommendApi.ts
  src/api/searchApi.ts
  src/api/trackApi.ts
  src/assets/icons/RectangleVertax.tsx
  src/assets/icons/SpotifyHover.tsx
  src/assets/icons/play/CirclePlaySmall.tsx
  src/assets/imgs/default_album_artist.png
  src/components/album/AlbumArtistInfo.tsx
  src/components/album/AlbumList.tsx
  src/components/artist/ArtistAlbumList.tsx
  src/components/artist/ArtistImage.tsx
  src/components/artist/ArtistTopTrack.tsx
  src/components/artist/RelatedArtist.tsx
  src/components/common/NavBar.tsx
  src/components/common/PlayBar.tsx
  src/components/common/Playnow.tsx
  src/components/common/StandardButton.tsx
  src/components/home/Banner.tsx
  src/components/home/BannerItem.tsx
  src/components/home/TopTrackItem.tsx
  src/components/home/TopTrackList.tsx
  src/components/home/index.tsx
  src/components/recommend/ArtistSelector.tsx
  src/components/recommend/TrackSelector.tsx
  src/components/search/SearchResultWrap.tsx
  src/constants/banner.ts
  src/constants/index.ts
  src/pages/Album.tsx
  src/pages/Artist.tsx
  src/pages/BillFromSpotify.tsx
  src/pages/Home.tsx
  src/pages/Recommend.tsx
  src/pages/Router.tsx
  tailwind.config.js
Labels: 기능 추가, 스타일, 수정 (리팩토링)

#39 ✨ feat: search, album, artist 페이지 기능 추가 및 스타일 수정
  src/api/searchApi.ts
  src/components/album/AlbumArtistInfo.tsx
  src/components/album/AlbumList.tsx
  src/components/artist/ArtistAlbumList.tsx
  src/components/artist/ArtistTopTrack.tsx
  src/components/artist/RelatedArtist.tsx
  src/components/bill/BillBox.tsx
  src/components/bill/BillButtonListSection.tsx
  src/components/bill/UserBillItem.tsx
  src/components/common/Header.tsx
  src/components/common/PlayBar.tsx
  src/components/common/index.ts
  src/components/common/item/AlbumItem.tsx
  src/components/common/item/ArtistItem.tsx
  src/components/common/item/PlaylistItem.tsx
  src/components/common/item/TrackItem.tsx
  src/components/common/item/index.ts
  src/components/home/BannerItem.tsx
  src/components/home/SimilarUser.tsx
  src/components/home/SimilarUserList.tsx
  src/components/home/TopTrackItem.tsx
  src/components/recommend/ArtistSelector.tsx
  src/components/recommend/GenreSelector.tsx
  src/components/recommend/RecommendArtistItem.tsx
  src/components/recommend/RecommendGenreItem.tsx
  src/components/recommend/RecommendTrackItem.tsx
  src/components/recommend/TrackSelector.tsx
  src/components/recommend/index.tsx
  src/components/search/RecentSearchList.tsx
  src/components/search/SearchBar.tsx
  src/components/search/SearchResultAlbum.tsx
  src/components/search/SearchResultArtist.tsx
  src/components/search/SearchResultArtistItem.tsx
  src/components/search/SearchResultPlaylist.tsx
  src/components/search/SearchResultTrack.tsx
  src/components/search/SearchResultTrackItem.tsx
  src/components/search/SearchResultWrap.tsx
  src/components/search/index.tsx
  src/hooks/index.ts
  src/hooks/useModal.ts
  src/hooks/useModal.tsx
  src/hooks/usePlayAndPausePreview.ts
  src/hooks/useSwipe.ts
  src/pages/Album.tsx
  src/pages/Artist.tsx
  src/pages/Bill.tsx
  src/pages/BillFromSpotify.tsx
  src/pages/Home.tsx
  src/pages/Layout.tsx
  src/pages/Search.tsx
  src/types/index.ts
  src/types/listSwipe.ts
  tailwind.config.js
Labels: 기능 추가, 스타일, 수정 (리팩토링)

#41 ✨ feat: bottomSheet type 및 기능 추가 (#40)
  src/assets/icons/BottomSheetTop.tsx
  src/components/common/BottomSheet.tsx
  src/components/common/item/PlaylistItem.tsx
  src/components/common/item/TrackItem.tsx
  src/components/search/SearchResultWrap.tsx
  src/constants/bottomSheeText.ts
  src/constants/buttonText.ts
  src/constants/index.ts
  src/hooks/useModal.ts
  src/index.css
  src/pages/Artist.tsx
Labels: 기능 추가, 스타일

#43 🐛 fix: bottomsheet animate 재 업로드 (#40)
  src/index.css
Labels: 버그, 스타일

#48 ♻️ refactor: 전역 라우터 설정 변경 외 #46
  package-lock.json
  package.json
  src/api/albumApi.ts
  src/api/artistApi.ts
  src/api/axios.ts
  src/api/getNoneMemberToken.ts
  src/api/index.ts
  src/api/playlistApi.ts
  src/api/recommendApi.ts
  src/api/searchApi.ts
  src/api/supabase/SpotifyAuthApis.ts
  src/api/supabase/pixelbeatAuthApis.ts
  src/api/supabase/tableAccessApis.ts
  src/api/trackApi.ts
  src/assets/imgs/index.ts
  src/assets/index.ts
  src/components/Profile/ProfileForm.tsx
  src/components/SignIn/SignInForm.tsx
  src/components/SignUp/SignUpForm.tsx
  src/components/search/SearchBar.tsx
  src/constants/ROUTES.ts
  src/constants/index.ts
  src/hooks/useUserSession.ts
  src/pages/Layout.tsx
  src/pages/Page-Album.tsx
  src/pages/Page-Artist.tsx
  src/pages/Page-Bill.tsx
  src/pages/Page-BillFromSpotify.tsx
  src/pages/Page-Entry.tsx
  src/pages/Page-Home.tsx
  src/pages/Page-MyMusicBill.tsx
  src/pages/Page-MyMusicBillId.tsx
  src/pages/Page-MyMusicMain.tsx
  src/pages/Page-Profile.tsx
  src/pages/Page-ProfileEdit.tsx
  src/pages/Page-Recommend.tsx
  src/pages/Page-RecommendEntry.tsx
  src/pages/Page-Search.tsx
  src/pages/Page-SigninWithEmail.tsx
  src/pages/Page-SignupGreeting.tsx
  src/pages/Page-SignupWithEmail.tsx
  src/pages/ProfileEdit.tsx
  src/pages/Router.tsx
  src/pages/index.ts
  src/types/commonTypes.ts
  src/types/index.ts
  src/utils/index.ts
  src/utils/loadTokenAndCheckExpiration.ts
  tsconfig.json
Labels: 기능 추가, 수정 (리팩토링)

#51 ♻️ refactor: Profile 컴포넌트 수정 외 다수 #50
  src/api/albumApi.ts
  src/api/artistApi.ts
  src/api/axios.ts
  src/api/playlistApi.ts
  src/api/recommendApi.ts
  src/api/searchApi.ts
  src/api/supabase/SpotifyAuthApis.ts
  src/api/supabase/index.ts
  src/api/trackApi.ts
  src/api/userApi.ts
  src/assets/icons/SmallBillSide.tsx
  src/assets/icons/Spinner.tsx
  src/assets/icons/index.ts
  src/assets/icons/moreCircle.tsx
  src/assets/icons/profile/FullHeart.tsx
  src/assets/icons/profile/MyProfileBill.tsx
  src/assets/imgs/smallBill.png
  src/components/bill/BillGraph.tsx
  src/components/common/NavBar.tsx
  src/components/home/Banner.tsx
  src/components/home/SimilarUserList.tsx
  src/components/home/TopTrackList.tsx
  src/components/myProfile/MyBillList.tsx
  src/components/myProfile/MyLikeBillList.tsx
  src/components/myProfile/MyProfileInfo.tsx
  src/components/myProfile/MyProfileLike.tsx
  src/components/myProfile/SmallBill.tsx
  src/components/myProfile/index.tsx
  src/components/recommend/ArtistSelector.tsx
  src/components/recommend/TrackSelector.tsx
  src/components/search/SearchResultWrap.tsx
  src/constants/ROUTES.ts
  src/constants/navBarText.ts
  src/hooks/useUserInfo.ts
  src/hooks/useUserSession.ts
  src/index.css
  src/pages/Page-Bill.tsx
  src/pages/Page-BillFromSpotify.tsx
  src/pages/Page-BillHasOwner.tsx
  src/pages/Page-Home.tsx
  src/pages/Page-MyMusic.tsx
  src/pages/Page-Profile.tsx
  src/pages/Page-Recommend.tsx
  src/pages/PrivateRoute.tsx
  src/pages/PublicRoute.tsx
  src/pages/Router.tsx
  src/pages/Wrapper.tsx
  src/types/commonTypes.ts
  src/utils/getUserId.ts
Labels: 기능 추가, 설정, 수정 (리팩토링)

#53 ✨ feat: 재생기능 DB연동 및 현재 재생목록 로직구현 외 다수
  src/api/supabase/index.ts
  src/api/supabase/playlistTableAccessApis.ts
  src/api/supabase/profilesTableAccessApis.ts
  src/assets/imgs/bannerBg_desktop.png
  src/assets/imgs/bannerBg_mobile.png
  src/assets/imgs/listmenu.png
  src/components/Login/index.ts
  src/components/MyMusic/MusicBill.tsx
  src/components/MyMusic/MusicList.tsx
  src/components/MyMusic/MusicListItem.tsx
  src/components/bill/BillBox.tsx
  src/components/bill/BillBoxHasOwner.tsx
  src/components/bill/BillButtonListSection.tsx
  src/components/bill/BillItem.tsx
  src/components/bill/UserBillItem.tsx
  src/components/common/PlayBar.tsx
  src/components/home/Banner.tsx
  src/components/home/ToRecommendBannerItem.tsx
  src/components/home/TopTrackItem.tsx
  src/constants/bottomSheeText.ts
  src/hooks/usePlayAndPausePreview.ts
  src/hooks/useUserSession.ts
  src/index.css
  src/pages/Page-Bill.tsx
  src/pages/Page-BillFromSpotify.tsx
  src/pages/Page-BillHasOwner.tsx
  src/pages/PrivateRoute.tsx
  src/pages/PublicRoute.tsx
  src/pages/Wrapper.tsx
  src/types/tracklist.ts
Labels: 버그, 기능 추가, 스타일, 수정 (리팩토링)

#55 ✨ feat: confirm 모달 구현 외 #52
  src/api/axios.ts
  src/api/getNoneMemberToken.ts
  src/api/supabase/pixelbeatAuthApis.ts
  src/api/supabase/playlistTableAccessApis.ts
  src/api/supabase/signInTableAccessApis.ts
  src/api/userApi.ts
  src/assets/icons/VisitorIcon.tsx
  src/assets/icons/index.ts
  src/assets/icons/profile/FullHeart.tsx
  src/assets/imgs/Logo.png
  src/components/ConfirmModal.tsx
  src/components/ErrorComponent.tsx
  src/components/SignIn/SignInForm.tsx
  src/components/bill/UserBillItem.tsx
  src/components/common/PixelBeatLoginButton.tsx
  src/components/common/SmallButton.tsx
  src/components/common/StandardButton.tsx
  src/components/common/index.ts
  src/components/index.ts
  src/components/recommend/ArtistSelector.tsx
  src/components/recommend/TrackSelector.tsx
  src/constants/ROUTES.ts
  src/constants/buttonText.ts
  src/pages/Page-Bill.tsx
  src/pages/Page-BillHasOwner.tsx
  src/pages/Page-Entry.tsx
  src/pages/Page-Recommend.tsx
  src/pages/Page-RecommendEntry.tsx
  src/pages/Page-SigninWithEmail.tsx
  src/pages/Page-SignupWithEmail.tsx
  src/pages/PrivateRoute.tsx
  src/pages/Router.tsx
  src/utils/getUserId.ts
  src/utils/loadTokenAndCheckExpiration.ts
Labels: 기능 추가, 스타일, 수정 (리팩토링)

#57 ✨ feat: useConfirm 구현 및 서치, 앨범, 가수 페이지의 재생 기능
  src/api/supabase/profilesTableAccessApis.ts
  src/components/ConfirmModal.tsx
  src/components/Profile/ProfileForm.tsx
  src/components/SignIn/SignInForm.tsx
  src/components/album/AlbumList.tsx
  src/components/artist/ArtistTopTrack.tsx
  src/components/artist/RelatedArtist.tsx
  src/components/bill/BillBox.tsx
  src/components/bill/BillBoxHasOwner.tsx
  src/components/bill/UserBillItem.tsx
  src/components/common/ConfirmModal.tsx
  src/components/common/SmallButton.tsx
  src/components/common/index.ts
  src/components/common/item/PlaylistItem.tsx
  src/components/common/item/TrackItem.tsx
  src/components/home/BannerItem.tsx
  src/components/index.ts
  src/components/search/SearchBar.tsx
  src/components/search/SearchResultPlaylist.tsx
  src/components/search/SearchResultTrack.tsx
  src/constants/bottomSheetText.ts
  src/constants/confirmText.ts
  src/constants/index.ts
  src/hooks/index.ts
  src/hooks/useConfirm.ts
  src/pages/Page-Album.tsx
  src/pages/Page-Artist.tsx
  src/pages/Page-BillHasOwner.tsx
  src/pages/Page-ProfileEdit.tsx
  src/pages/Page-Search.tsx
  src/pages/Page-SignupWithEmail.tsx
  src/pages/PrivateRoute.tsx
  src/zustand/confirmStore.ts
  src/zustand/index.ts
Labels: 기능 추가, 스타일

#59 ✨ feat: mymusic 음악서랍 기능 구현 및 마크업
  src/api/supabase/playlistTableAccessApis.ts
  src/assets/icons/moreCircle.tsx
  src/components/MyMusic/MusicBill.tsx
  src/components/MyMusic/MusicBillId.tsx
  src/components/MyMusic/MusicList.tsx
  src/components/MyMusic/index.tsx
  src/components/myMusic/MusicShelf.tsx
  src/components/myMusic/MusicShelfItem.tsx
  src/constants/ROUTES.ts
  src/pages/Page-MyMusic.tsx
  src/pages/Page-MyMusicBillId.tsx
  src/pages/Page-MyMusicShelfDetail.tsx
Labels: 기능 추가, 스타일

#63 🐛 fix: 재생목록에서 삭제 시 현재 재생곡이 유지되는 문제 해결
  src/api/supabase/pixelbeatAuthApis.ts
  src/api/supabase/profilesTableAccessApis.ts
  src/components/MyMusic/MusicList.tsx
  src/components/Profile/ProfileForm.tsx
  src/components/SignUp/SignUpForm.tsx
  src/components/common/PlayBar.tsx
  src/components/common/ProgressBar.tsx
  src/components/index.ts
  src/components/myMusic/MusicShelfItem.tsx
  src/components/myProfile/SmallBill.tsx
  src/hooks/usePlayAndPausePreview.ts
  src/pages/Page-BillHasOwner.tsx
  src/pages/Page-MyMusicShelfDetail.tsx
  src/pages/Page-ProfileEdit.tsx
  src/pages/Page-Recommend.tsx
  src/zustand/confirmStore.ts
  src/zustand/modalStore.ts
Labels: 버그

#65 🧪 test: 배포 테스트 #64
  src/components/SignIn/SignInForm.tsx
  src/components/SignIn/index.tsx
  src/components/SignUp/SignupInputField.tsx
  src/components/common/Header.tsx
  src/components/recommend/ArtistSelector.tsx
  src/components/recommend/GenreSelector.tsx
  src/components/recommend/TrackSelector.tsx
  src/pages/Page-Recommend.tsx
Labels: 수정 (리팩토링)

#66 🎨 style: pc버전 배경 효과 및 스타일 정리
  index.html
  public/pixelbeat.svg
  public/vite.svg
  src/assets/icons/BottomSheetTop.tsx
  src/assets/icons/SpotifyLoginButton.tsx
  src/assets/icons/VisitorIcon.tsx
  src/assets/icons/home/SearchIcon.tsx
  src/assets/imgs/screenBgGreen.png
  src/assets/imgs/topBar.png
  src/components/ErrorComponent.tsx
  src/components/album/AlbumArtistInfo.tsx
  src/components/album/AlbumList.tsx
  src/components/artist/ArtistAlbumList.tsx
  src/components/artist/ArtistImage.tsx
  src/components/artist/ArtistTopTrack.tsx
  src/components/common/BottomSheet.tsx
  src/components/common/Header.tsx
  src/components/common/MatrixBackground.tsx
  src/components/common/NavBar.tsx
  src/components/common/PlayBar.tsx
  src/components/common/ProgressBar.tsx
  src/components/common/ScreenBackground.tsx
  src/components/common/item/AlbumItem.tsx
  src/components/common/item/ArtistItem.tsx
  src/components/common/item/PlaylistItem.tsx
  src/components/common/item/TrackItem.tsx
  src/components/home/Banner.tsx
  src/components/home/SimilarUserList.tsx
  src/components/home/TopTrackItem.tsx
  src/components/home/TopTrackList.tsx
  src/components/search/RecentSearchList.tsx
  src/components/search/SearchBar.tsx
  src/components/search/SearchResultAlbum.tsx
  src/components/search/SearchResultArtist.tsx
  src/components/search/SearchResultPlaylist.tsx
  src/components/search/SearchResultTrack.tsx
  src/components/search/SearchResultWrap.tsx
  src/constants/errorText.ts
  src/hooks/useModal.ts
  src/index.css
  src/pages/Page-Search.tsx
  src/pages/Wrapper.tsx
  tailwind.config.js
  tsconfig.json
Labels: 스타일, 수정 (리팩토링)

#69 Fix/#67
  src/api/supabase/spotifyAuthApis.ts
  src/components/artist/ArtistImage.tsx
  src/components/bill/BillBoxHasOwner.tsx
  src/components/home/SimilarUserBill.tsx
  src/components/home/SimilarUserList.tsx
  src/components/home/TopTrackItem.tsx
  src/components/myMusic/MusicList.tsx
  src/components/myMusic/MusicListItem.tsx
  src/components/myMusic/index.tsx
  src/components/myProfile/MyLikeBillList.tsx
  src/components/profile/ImageUploadForm.tsx
  src/components/profile/ProfileForm.tsx
  src/components/profile/ProfileInputField.tsx
  src/components/profile/index.tsx
  src/components/signIn/InputSection.tsx
  src/components/signIn/SignInForm.tsx
  src/components/signIn/SigninInputField.tsx
  src/components/signIn/index.tsx
  src/components/signUp/NavigateAssistPopUp.tsx
  src/components/signUp/SignUpForm.tsx
  src/components/signUp/SignupInputField.tsx
  src/components/signUp/ValidationErrorMessage.tsx
  src/components/signUp/index.tsx
  src/constants/confirmText.ts
  src/pages/Page-Bill.tsx
  src/pages/Wrapper.tsx
  vite.config.ts
Labels: 수정 (리팩토링)

#74 ♻️ refactor: home의 인기영수증 로직 수정
  src/api/supabase/playlistTableAccessApis.ts
  src/assets/icons/RectangleVertax.tsx
  src/assets/icons/StandardVertex.tsx
  src/components/home/PopularUserBill.tsx
  src/components/home/PopularUserList.tsx
  src/components/home/index.tsx
  src/components/myProfile/MyBillList.tsx
  src/components/myProfile/MyLikeBillList.tsx
  src/components/myProfile/SmallBill.tsx
  src/pages/Page-Home.tsx
Labels: 수정 (리팩토링)

#77 ♻️ refactor: 추천 로직: 비동기 에러 해결 #76
  src/api/supabase/playlistTableAccessApis.ts
  src/api/supabase/profilesTableAccessApis.ts
  src/api/trackApi.ts
  src/components/profile/ProfileForm.tsx
  src/components/recommend/TrackSelector.tsx
  src/constants/ROUTES.ts
  src/pages/Page-Recommend.tsx
  src/types/tracklist.ts
Labels: 버그, 수정 (리팩토링)

#75 📝 docs: README 작성 (#70)
  README.md
Labels: 설정
